*&---------------------------------------------------------------------*
*& Include ZPPB001_SCREEN
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK BK3 WITH FRAME TITLE TEXT-003.
PARAMETERS:
  RB_IN  RADIOBUTTON GROUP R2 DEFAULT 'X' USER-COMMAND IO,
  RB_OUT RADIOBUTTON GROUP R2.
SELECTION-SCREEN END OF BLOCK BK3.


*导入界面
SELECTION-SCREEN BEGIN OF BLOCK BK1 WITH FRAME TITLE TEXT-001.

PARAMETERS:
  RB_INS RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND RB MODIF ID G1,
  RB_UPD RADIOBUTTON GROUP R1 MODIF ID G1,
  RB_DEL RADIOBUTTON GROUP R1 MODIF ID G1.
SELECTION-SCREEN SKIP 1.

*SELECT-OPTIONS s1_werks FOR mast-werks MODIF ID g3." OBLIGATORY.
PARAMETERS:P1_STLAN TYPE  MAST-STLAN MODIF ID G3 DEFAULT '1' ." OBLIGATORY.

SELECTION-SCREEN SKIP 1.
PARAMETERS: P_UFILE TYPE RLGRAP-FILENAME MODIF ID G1.
*                         DEFAULT 'D:\BOM创建修改删除模板.XLSX'.

*--LUZY 添加选择导入格式的按钮
PARAMETERS RB_TXT AS CHECKBOX  USER-COMMAND RB MODIF ID G1.


SELECTION-SCREEN END OF BLOCK BK1.



*导出界面
SELECTION-SCREEN BEGIN OF BLOCK BK2 WITH FRAME TITLE TEXT-002.

SELECT-OPTIONS:
  S_WERKS  FOR CSAP_MBOM-WERKS MODIF ID G2 OBLIGATORY, "工厂
  S_MATNR  FOR MARA-MATNR MODIF ID G2,            "料号
  S_STLAL  FOR MAST-STLAL MODIF ID G2.
PARAMETERS:
  P_ANDAT  TYPE STKO-DATUV OBLIGATORY DEFAULT SY-DATUM MODIF ID G2.
PARAMETERS:
  PM_EHNDL(1) TYPE C     DEFAULT '1' NO-DISPLAY,
  P_STLAN     TYPE MAST-STLAN MODIF ID G2 DEFAULT '1',           "BOM用途           "创建日期  有效日期
  P_BWKEY     TYPE MBEW-BWKEY MODIF ID G2 NO-DISPLAY.                      "估价范围
SELECTION-SCREEN SKIP 1.
PARAMETERS:
  RB_DAN RADIOBUTTON GROUP R3 DEFAULT 'X' USER-COMMAND OI MODIF ID G2,
  RB_DUO RADIOBUTTON GROUP R3 MODIF ID G2.


SELECTION-SCREEN END OF BLOCK BK2.
